#!/bin/bash

source "${HOME}/.local/share/chezmoi/lib/libcore.sh"

trap '(exit 130)' INT
trap '(exit 143)' TERM
trap 'rc=$?; handler $rc; exit $rc' EXIT

readonly SCRIPT_URL='https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh'
readonly DOT_TEMPDIR="$(mktemp -d)"
readonly DOT_LOGFILE="$(mktemp /tmp/install_lvim_log.XXXXXX)"

main() {
  tput civis
  if ! install_lvim; then
    return 1
  fi
  tput cnorm
}

install_lvim() {
  if [[ "$(command -v lvim)" ]] || [[ -f ".local/bin/lvim" ]]; then
    succ 'Skipping installation, LunarVim is already installed'
    return 0
  fi
  wait_strt 'Downloading LunarVim install script'
  http_file "${SCRIPT_URL}" "${DOT_TEMPDIR}/install.sh"
  local rc=$?
  case $rc in
    0) wait_succ 'Downloading LunarVim install script, done' ;;
    *) wait_fail 'Downloading LunarVim install script, failed'; return $rc ;;
  esac
  DOT_WAIT_FLT=1 LV_BRANCH='release-1.2/neovim-0.8' wait_strt 'Executing LunarVim install script'
  /bin/bash "${DOT_TEMPDIR}/install.sh" --yes >> "${DOT_LOGFILE}" 2>&1
  rc=$?
  case $rc in
    0) DOT_WAIT_FLT=1 wait_succ 'Executing LunarVim install script, done' ;;
    *) DOT_WAIT_FLT=1 wait_fail 'Executing LunarVim install script, failed'; return $rc ;;
  esac
}

main "$@"

